Config = {

    docTexts = {
        ["csc_doc_a"] = [[
            L'entreprise a enregistré un chiffre d'affaires de 43 000 $ durant la période écoulée, un résultat relativement satisfaisant au regard des objectifs fixés. Cependant, ce chiffre n'a pas permis de couvrir les dépenses internes, qui se sont élevées à 42 500 $, principalement en raison des coûts liés aux salaires, à la gestion des ressources et à l'entretien des équipements. De plus, les dépenses globales, comprenant des frais de marketing et des investissements divers, ont atteint 41 000 $. Ces charges cumulées ont entraîné un déséquilibre financier majeur.

            En conséquence, l'entreprise se trouve dans une situation où ses dépenses dépassent de manière inquiétante ses recettes, malgré un chiffre d'affaires relativement stable. Une révision complète de la structure des coûts s'avère indispensable pour rétablir l'équilibre financier. Il sera crucial de réduire les dépenses internes en priorisant les investissements essentiels et d'optimiser les coûts opérationnels. Par ailleurs, une évaluation des dépenses globales, notamment en matière de marketing et de projets non essentiels, permettra de limiter les impacts négatifs sur la rentabilité.
            ]],
        ["csc_doc_b"] = [[
            L’entreprise a généré un chiffre d’affaires de 41 500 $, ce qui pourrait sembler une performance acceptable, si l’on oublie les petites "détails" comme les dépenses internes, qui ont atteint la modeste somme de 33 000 $. Oui, vous avez bien lu : 33 000 $. En grande partie grâce à des choix stratégiques tels que des salaires généreusement élevés et des investissements dans des équipements de pointe dont on se demande si l’entreprise en a réellement besoin. Et bien sûr, ce n’est pas tout, car les dépenses globales, incluant marketing, services externes et autres « investissements stratégiques », ont ajouté 31 000 $ supplémentaires. C'est toujours un plaisir d’ajouter une couche de dépenses superflues quand on essaie de maintenir un équilibre financier… qui se trouve manifestement en déséquilibre complet.

            Avec un total de 64 000 $ de dépenses pour un chiffre d’affaires de 41 500 $, l’entreprise se retrouve, sans grande surprise, dans une situation où la rentabilité n'est qu'un lointain souvenir. Mais ne vous inquiétez pas, tout n’est pas perdu ! Il suffit de couper dans les dépenses internes, n'est-ce pas ? Peut-être une légère réduction des salaires ou une suppression des investissements inutiles, comme ceux qui sont censés “améliorer la visibilité” mais qui ne font qu’amplifier les pertes. Quant aux dépenses globales, elles méritent également une révision, car on pourrait se demander si toutes ces dépenses marketing sont vraiment justifiées. Si l’entreprise veut un jour revoir la couleur du profit, une approche plus réaliste et moins exubérante s'impose, mais bon, qui aime être réaliste de nos jours ?
            ]],
        ["csc_doc_c"] = [[
            04/01/1999

            L'année commence sur une note encourageante avec un chiffre d'affaires de 42 000 $, témoignant d'une bonne dynamique commerciale. Cependant, comme tout succès a son coût, les dépenses internes ont atteint 23 000 $, notamment en raison des investissements dans les équipes et les infrastructures. Ces dépenses, bien qu'importantes, reflètent l'engagement de l’entreprise à maintenir un fonctionnement de qualité et à répondre aux attentes croissantes de ses clients.

            Du côté des dépenses globales, celles-ci s’élèvent à 21 000 $, incluant des initiatives de communication et de développement stratégique. Bien qu'elles ajoutent une pression supplémentaire sur la rentabilité, elles sont essentielles pour soutenir la croissance future. Avec une gestion attentive et des ajustements prudents, ce début d’année prometteur pourrait marquer une étape importante vers un équilibre durable entre les revenus et les charges. Gardons l’optimisme : tout grand succès commence par un ajustement bien calculé !
            ]],
        ["csc_doc_d"] = [[
            L’année 2004 s’ouvre avec un chiffre d’affaires solide de 44 000 $, marquant une étape importante dans la quête de performance de l’entreprise. Ce résultat est le fruit d’un travail acharné, d’une stratégie commerciale réfléchie et de l’engagement sans faille des équipes. Cependant, maintenir cette dynamique a nécessité des efforts financiers notables, avec des dépenses internes s’élevant à 12 000 $, principalement pour soutenir les opérations et motiver le personnel. Chaque dollar investi a été pensé pour garantir la continuité d’une croissance durable et la qualité des services offerts.

            En parallèle, les dépenses globales ont atteint 14 000 $, intégrant des actions stratégiques comme l’expansion des campagnes marketing et le renforcement des partenariats externes. Ces efforts, bien que coûteux, témoignent de la volonté de l’entreprise de s’imposer comme un acteur de premier plan. La gestion rigoureuse des ressources et l’audace dans les choix stratégiques confirment la vision ambitieuse de l’entreprise. Ce début d’année est un pas de plus vers un avenir où chaque défi surmonté renforce la détermination et pave le chemin vers l’excellence.
            ]],
        ["csc_doc_e"] = [[
            Compte rendu économique - 10/10/2023

            Dans un revirement inattendu, l'entreprise a enregistré un chiffre d'affaires de 32 000 $ au cours de la dernière période. Si ce montant montre une certaine activité, il est bien loin de compenser les dépenses internes, qui se sont envolées à 41 500 $. Ces coûts, majoritairement liés à des augmentations salariales et à des projets opérationnels d'envergure, semblent avoir dépassé les prévisions de manière inattendue. Ce déséquilibre soulève une question évidente : comment une telle déviation a-t-elle pu passer sous le radar jusqu’à maintenant ?

            À cela s’ajoutent des dépenses globales de 34 000 $, notamment dues à des initiatives ambitieuses en marketing et en partenariats stratégiques. Bien que ces dépenses puissent porter leurs fruits à long terme, elles alourdissent considérablement la situation actuelle. Avec un total de 75 500 $ de charges contre un revenu bien inférieur, la surprise n’est pas tant dans les chiffres que dans le contraste saisissant entre ambition et réalité. Une réévaluation immédiate des priorités financières s’impose pour éviter que cette situation, déjà inattendue, ne dégénère davantage.
            ]],
        ["csc_doc_f"] = [[
            L’entreprise, à la date du 11/06/2008, affiche un chiffre d’affaires de 33 500 $. Ce résultat, bien qu’encourageant par certains aspects, laisse entrevoir un potentiel inexploité qu’il serait grand temps de développer. Cependant, la gestion des dépenses internes montre une maîtrise raisonnable avec un montant de 32 000 $, principalement dirigé vers les opérations courantes et les charges salariales. On pourrait dire que ces efforts maintiennent un équilibre précaire, mais il est clair qu’une réflexion plus profonde sur l’allocation des ressources internes ne ferait pas de mal.

            Là où le bât blesse véritablement, c’est au niveau des dépenses globales. Avec un total de 45 000 $, celles-ci excèdent largement ce que l’entreprise peut se permettre dans la conjoncture actuelle. Entre des campagnes marketing ambitieuses et des projets à long terme qui peinent à montrer leurs retombées immédiates, ces chiffres doivent pousser à une remise en question. Il est crucial de se souvenir que tout investissement doit s’inscrire dans une logique de retour sur capital. À ce stade, une posture proactive et un effort collectif pour revoir la stratégie s’imposent si l’on veut éviter que ces écarts ne deviennent des habitudes coûteuses. Soyons réalistes, mais aussi bienveillants : il est encore temps de redresser la barre avec un peu de discipline.
            ]],
        ["csc_doc_g"] = [[
            Le chiffre d’affaires de l’entreprise s’élève à 34 000 $ pour cette période, un résultat honorable mais qui pourrait encore être optimisé. Il est clair que nous sommes sur la bonne voie, mais il est aussi évident que certains ajustements sont nécessaires pour poursuivre cette croissance. En effet, les dépenses internes ont atteint 22 000 $, principalement en raison de l’augmentation des coûts de production et des frais associés aux opérations quotidiennes. Bien que ces dépenses soient justifiées, il est important de souligner que nous devons rester vigilants afin de ne pas perdre de vue l’équilibre financier. Claude Munez, bien que dans un rôle de moindre envergure, a déjà suggéré plusieurs pistes pour rationaliser ces coûts. Ces idées, s’elles sont mises en œuvre de manière réfléchie, pourraient améliorer l’efficacité opérationnelle.

            En parallèle, les dépenses globales ont représenté 12 500 $, englobant les coûts liés à la gestion de la communication externe et à l’acquisition de nouveaux outils technologiques. Ces investissements sont certes nécessaires pour l’avenir, mais ils doivent être soigneusement gérés pour éviter des dérives budgétaires. Si l’on veut continuer à progresser tout en maîtrisant nos charges, il sera crucial de redéfinir certaines priorités. L’équipe, et en particulier Claude Munez, a tout à fait conscience des enjeux et reste mobilisée pour garantir que chaque dollar dépensé se traduise par une réelle valeur ajoutée. Avec une gestion plus serrée et une attention accrue aux détails, nous pourrions voir de nouveaux succès dès l’année prochaine.
            ]],
        ["csc_doc_h"] = [[
            Au 12/02/1997, l’entreprise a enregistré un chiffre d’affaires de 31 500 $, un montant respectabilisé, mais qui ne doit pas nous faire perdre de vue les objectifs ambitieux que nous nous étions fixés. Ce chiffre, bien qu’encourageant, laisse entrevoir des possibilités d’optimisation dans certains secteurs. En parallèle, les dépenses internes se sont élevées à 13 000 $, principalement dues à des coûts liés à la gestion des ressources humaines et à l’entretien des infrastructures. Bien que ces dépenses soient nécessaires, il est important de rester vigilant pour éviter des hausses continues qui pourraient mettre en péril notre capacité à investir dans d'autres domaines. Madame Walker, en tant qu’agent de police, a observé une augmentation des dépenses en sécurité, et elle a suggéré quelques ajustements qui pourraient avoir un impact positif à court terme.

            Quant aux dépenses globales, elles ont atteint 22 500 $, une somme qui inclut des investissements en marketing et dans le développement d'outils technologiques. Bien que ces dépenses soient cruciales pour maintenir la compétitivité de l'entreprise, il serait sage d’adopter une approche plus sélective afin de maximiser leur efficacité. L’équipe, et notamment Madame Walker dans son domaine d’intervention, reste consciente de la nécessité de contrôler les coûts tout en continuant à se développer. Il est essentiel de rappeler que chaque dollar investi doit viser à améliorer nos marges et non à augmenter nos charges de manière disproportionnée. Avec une gestion plus serrée, nous serons capables de générer de la valeur tout en maintenant un équilibre financier sain.
            ]],
        ["csc_doc_i"] = [[
            Le 14 août 2021, l'entreprise a enregistré un chiffre d'affaires de 22 500 $, un résultat qui montre que nous restons dans la course, mais il reste encore beaucoup de travail pour atteindre notre plein potentiel. Bien que ce chiffre soit solide, il ne reflète pas encore le niveau de performance que nous visons. En revanche, les dépenses internes ont atteint 43 000 $, principalement dues aux coûts liés à la gestion des ressources humaines et à l’amélioration des équipements de production. Il est évident que nous devons être plus agiles et concentrer nos efforts pour réduire ces dépenses tout en maintenant notre niveau d’activité. Comme un athlète qui doit affiner ses techniques pour se surpasser, nous devons ajuster notre stratégie pour devenir plus efficaces et plus rentables.

            En ce qui concerne les dépenses globales, elles ont atteint 24 000 $, une part importante étant attribuée à des investissements stratégiques et à des partenariats avec des prestataires comme "Turbo Fitness 2000". Cette collaboration, bien qu'essentielle, entraîne des frais élevés. Cependant, ces investissements peuvent être comparés à l'entraînement intensif d'un sportif : nécessaires pour se renforcer et se préparer à la performance à long terme. Il est maintenant temps d’adopter une approche encore plus ciblée et de maximiser chaque dépense pour transformer l'effort en résultats. Nous avons la capacité de progresser, et en réajustant nos priorités, nous pourrons franchir la ligne d'arrivée avec des résultats encore plus impressionnants.
            ]],
        ["csc_doc_j"] = [[
            Le 15 mai 1994, l'entreprise a généré un chiffre d'affaires de 22 500 $, un bon petit coup de vent pour commencer la journée, mais il nous faut encore plus de courage pour traverser la tempête. Bien que cette somme soit respectée, elle reste insuffisante pour maintenir le rythme de croisière que l’on recherche. Parallèlement, les dépenses internes ont été de 32 000 $, un total non négligeable qui s’est envolé pour des opérations quotidiennes, des salaires et quelques petites réparations. Mais comme dans le grand Ouest, faut pas hésiter à mettre un peu d’huile dans la machine quand elle commence à grincer, tout en veillant à ce que l’argent ne coule pas plus vite qu’une rivière en crue. Monsieur Marston, notre agent d'entretien indépendant, a donné son avis sur certains travaux qu'il estime inutiles et pourrait bien nous aider à réduire cette facture si nous le laissons faire.

            Les dépenses globales se sont élevées à 12 000 $, pour diverses charges liées aux fournisseurs et à l’achat de nouveaux équipements. Ces dépenses sont nécessaires, certes, mais elles doivent être gérées comme une vraie chevauchée. Pas question de faire n'importe quoi en dépensant plus que de raison. Si l'on veut éviter de finir comme un cow-boy sans sa monture, il va falloir maîtriser ces dépenses et les adapter à la réalité de la prairie financière. À la fin de la journée, chaque dollar compte, et avec un peu de prudence et une volonté de fer, on pourra faire de cette entreprise une légende du Far West des affaires. On garde les yeux sur l’horizon, partenaire, et on avance, un pas à la fois.
            ]],
        ["csc_doc_k"] = [[
            Le 16 octobre 2002, l'entreprise a généré un chiffre d'affaires de 21 500 $, ce qui est loin d'être suffisant au regard de la situation actuelle. Bien que ce chiffre soit un début, il est tout à fait inadmissible qu'il ne dépasse pas ce seuil, surtout lorsque l’on observe les dépenses internes qui ont atteint 22 000 $. Les coûts liés à la gestion des ressources humaines et à l'entretien des équipements sont trop élevés, et il est clair qu'une révision drastique de nos pratiques internes s'impose. Nous ne pouvons pas continuer à nous permettre de telles dépenses sans mettre en place une stratégie stricte pour les limiter. Madame Collet, notre huissière , a déjà commencé à rappeler que ces dérives pourraient, à terme, avoir des conséquences graves sur notre liquidité et notre crédibilité financière.

            Les dépenses globales, quant à elles, se sont élevées à 42 000 $, un montant faramineux qui ne peut être justifié dans la situation actuelle. Ces dépenses incluent des investissements qui, bien que nécessaires, ont été mal dosés et auraient dû faire l'objet d'une analyse plus rigoureuse. Il est impératif que chaque centime soit désormais scruté, et toute dépense superflue sera catégoriquement rejetée. La direction doit prendre conscience que le temps des indulgences est révolu. Nous devons rapidement inverser cette tendance si nous ne voulons pas risquer des conséquences fâcheuses. La discipline est désormais la priorité absolue, et toute tentative de détourner l'attention de cette exigence stricte sera fermement réprimée.
            ]],
        ["csc_doc_l"] = [[
            Le 17 mars 1999, l'entreprise a enregistré un chiffre d'affaires de 23 500 $. C'est un bon début, mais ce n'est pas encore le genre de montant qui va faire exploser les feux d'artifice. Ce chiffre, bien qu'honorable, aurait pu être plus élevé si certaines décisions avaient été prises avec un peu plus de panache. Par ailleurs, les dépenses internes se sont élevées à 12 000 $, ce qui est plutôt raisonnable, mais encore une fois, ce n'est pas avec ce genre de dépenses qu'on va se retrouver dans la cour des grands. Une partie de cette somme a été utilisée pour de petits ajustements ici et là, mais si on veut vraiment briller, il va falloir rationaliser un peu ces coûts, sinon on va finir par ressembler à un éléphant dans un magasin de porcelaine. 

            Les dépenses globales, quant à elles, ont atteint la coquette somme de 32 000 $. Une grosse partie de cette facture provient de notre prestataire de Scranton, dont les services sont essentiels mais qui, parfois, semble prendre un peu trop de liberté avec les chiffres. Peut-être qu'ils pensent que la "Saint-Patrick" est une occasion pour facturer un peu plus, mais il va falloir discuter sérieusement de certaines lignes de facturation. Il est temps d'ajuster la stratégie et de mettre un peu d'humour dans les négociations, mais pas dans le budget, surtout si on ne veut pas finir la journée à sec. Bref, tout ça est gérable, mais attention à ne pas perdre de vue le principal : l'équilibre entre gains et dépenses.
            ]],
        ["csc_doc_m"] = [[
            Le 18 novembre 2019, l'entreprise a enregistré un chiffre d'affaires de 12 500 $. Une belle performance, certes, mais c'est loin d'être suffisant face à la situation alarmante qui se profile. En effet, les dépenses internes se sont envolées à 42 000 $, un montant tout bonnement incroyable pour une entreprise de notre taille. À ce rythme, il est difficile de croire que nous pourrons continuer à fonctionner sans revoir sérieusement notre manière de gérer les ressources. Il semble qu'on soit sur une pente glissante, avec des coûts internes qui semblent totalement hors de contrôle. Comment en sommes-nous arrivés là ? Une question légitime que tout le monde se pose.

            En parallèle, les dépenses globales ont atteint 13 000 $, une somme qui semble, en comparaison, presque raisonnable. Mais même cette facture, bien que plus modeste, ne nous donne aucun répit. L'écart entre nos revenus et nos dépenses est tout simplement choquant. Si nous ne trouvons pas rapidement une solution pour ajuster cette dynamique, il est évident que nous allons nous retrouver dans une situation plus que délicate. La question qui se pose maintenant est la suivante : comment rectifier le tir avant qu'il ne soit trop tard ? Parce qu'à ce rythme, on risque de se retrouver dans une position encore plus précaire.
            ]],
        ["csc_doc_n"] = [[
            Le 21 février 1998, l'entreprise, telle une barque fragile sur des eaux tumultueuses, a enregistré un chiffre d'affaires de 12 500 $, une somme qui, bien que modeste, évoque la lumière lointaine au bout d’un tunnel obscur. Ce chiffre, tout en étant honorable dans son contexte, n'est cependant pas suffisant pour apaiser les craintes qui se dessinent à l’horizon. Les dépenses internes, tel un fardeau pesant sur nos épaules, se sont élevées à 31 000 $. Il est regrettable de constater que ces coûts, loin de s'atténuer, croissent avec une insistance qui frôle l’insoutenable. Nos efforts pour les maîtriser semblent aussi vains que tenter de retenir l’eau d’un ruisseau avec ses mains nues.

            Et pourtant, les dépenses globales, bien qu’inférieures à celles-ci, ont atteint la somme de 22 000 $. Une charge certes plus modeste, mais qui s’ajoute à l’ensemble du fardeau financier et renforce la lourdeur du fardeau que nous portons. Nos perspectives de croissance, jadis lumineuses, semblent désormais assombries par l’ombre de ces engagements financiers. À moins de trouver une solution audacieuse et sage, il nous faudra naviguer prudemment, tel un vaisseau perdu, pour éviter que ces vents contraires ne nous précipitent vers des eaux plus dangereuses encore.
            ]],
        ["csc_doc_o"] = [[
            Le 21 mars 2017, l'entreprise a généré un chiffre d'affaires de 11 500 $. Un chiffre qui, dans le contexte économique actuel, pourrait sembler acceptable. Mais, en réalité, ce montant ne fait que souligner l'écart abyssal avec nos dépenses. Les dépenses internes, qui ont atteint 22 000 $, continuent de croître, malgré les multiples tentatives pour les contenir. Une bonne partie de cette somme a été allouée à l'entretien et à la mise à jour de notre studio de shooting fond vert, une dépense censée booster notre production. Malheureusement, cet investissement n'a pas porté les fruits escomptés. Il devient de plus en plus évident que nous avons misé sur la mauvaise stratégie, en espérant que cet équipement de pointe pourrait justifier les coûts élevés.

            À côté de cela, les dépenses globales, s’élevant à 32 000 $, sont tout aussi accablantes. En dépit de la qualité des équipements et des services proposés, les résultats ne suivent pas. L'écart entre ce que nous dépensons et ce que nous rapportons est devenu trop grand pour ignorer plus longtemps. Nos espérances, alimentées par des projets ambitieux, s'effondrent lentement, et la réalité s'impose de manière implacable. Il est désormais clair que nous devons réévaluer notre modèle économique et, peut-être, faire face à des décisions difficiles.
            ]],
        ["csc_doc_p"] = [[
            Le 22 janvier 2001, l'entreprise a enregistré un chiffre d'affaires de 13 500 $, un montant qui, même s'il peut paraître modeste au premier abord, témoigne de la dynamique impressionnante dans laquelle nous sommes engagés. Bien sûr, ce chiffre reste en deçà de nos ambitions, mais il est essentiel de noter que notre croissance s'est accélérée, et ce n'est que le début de notre aventure. Nos dépenses internes, quant à elles, se sont élevées à 12 000 $, une somme raisonnable compte tenu des efforts nécessaires pour maintenir nos opérations en marche, en particulier avec les dépenses liées à l’ouverture de nouvelles succursales. Ces investissements sont cruciaux pour étendre notre réseau et attirer plus de clients à travers de nouvelles régions. Nous voyons déjà des signes de retour positif sur ces investissements, avec des prospects et des opportunités qui se multiplient.

            Cependant, nos dépenses globales ont atteint 42 000 $, un chiffre qui, bien que plus élevé que prévu, est en grande partie attribuable à l'expansion rapide de notre réseau de succursales et à des frais marketing nécessaires pour soutenir notre visibilité. Ces coûts ne sont qu'une partie du processus d'implantation sur le marché, et nous restons confiants que cette stratégie portera ses fruits à moyen terme. La phase de transition est toujours la plus coûteuse, mais c'est aussi celle où l'on prépare les bases solides de l'avenir. Nous sommes en pleine croissance, et cette dynamique ne fait que commencer – les prochains mois devraient être excitants avec des résultats qui, nous en sommes convaincus, dépasseront nos attentes.
            ]],
        ["csc_doc_q"] = [[
            Le 26 octobre 2002, l'entreprise a généré un chiffre d'affaires de 42 000 $, un montant qui, ma foi, ne passe pas inaperçu. Cependant, la magie de la gestion financière nous rappelle que même les plus beaux chiffres ne sont que des chiffres. Nos dépenses internes, bien que nécessaires pour l'équilibre de l'entreprise, ont atteint 23 000 $. Parmi ces dépenses, nous avons fait l'acquisition d'un siège massant de qualité supérieure, un investissement sensé augmenter la productivité par un bien-être accru. De plus, dans un élan un peu extravagant, un petit budget a été alloué à l'achat de poissons exotiques pour créer une ambiance zen et inspirante dans nos bureaux. Ces choix sont certes singuliers, mais la créativité ne se limite pas à la rentabilité immédiate.

            Quant à nos dépenses globales, elles se sont élevées à 33 000 $. Ces coûts ont été principalement associés à l'élargissement de notre présence et à des campagnes marketing. Cependant, l'achat de poissons exotiques et du siège massant, bien que non conventionnels, ont apporté une touche d’originalité et un souffle nouveau à notre quotidien. Ces dépenses semblent extravagantes, mais qui peut réellement mesurer la valeur d’un bien-être collectif dans la quête de la performance ? Le reste des fonds a été judicieusement utilisé pour maintenir le cap et viser de nouveaux horizons. Bref, une gestion digne de ce nom, mais avec une touche de folie qui pourrait, qui sait, bien nous surprendre.
            ]],
        ["csc_doc_r"] = [[
            Le 26 novembre 1994, notre entreprise a généré un chiffre d’affaires de 31 500 $, un montant qui, bien que modeste, témoigne de la robustesse de nos activités et de la solidité de notre gestion. Il ne faut pas oublier que chaque étape, chaque chiffre est une victoire. Nos dépenses internes, s’élevant à 13 000 $, ont été judicieusement réparties entre les frais de fonctionnement quotidiens et l'aménagement de notre projet phare : l'agrandissement des archives. C'est un investissement de grande envergure qui se révèle nécessaire pour faire face à l’accumulation exponentielle de documents au sein de notre organisation. Un projet qui permettra d'augmenter notre capacité de stockage et de garantir la pérennité d’un système de gestion documentaire toujours plus exigeant.

            En parallèle, nos dépenses globales ont atteint 12 500 $, réparties de manière stratégique. Une partie de ces fonds a été allouée spécifiquement à l’agrandissement des archives, tandis que le reste a été utilisé pour maintenir et améliorer le cadre de travail existant. Bien que certains puissent juger ces investissements un peu rétrogrades, il n’en reste pas moins que ces choix sont indispensables pour maintenir une organisation solide et organisée. Nous sommes convaincus que ces efforts à long terme nous permettront de renforcer notre infrastructure et de préparer l’entreprise à un avenir toujours plus exigeant et structuré.
            ]],
        ["csc_doc_s"] = [[
            Le 27 juillet 1995, l'entreprise a généré un chiffre d'affaires de 22 500 $. Bien que certains puissent considérer ce montant comme modeste, il faut comprendre que ce chiffre est le produit de l'excellence et du travail acharné qui caractérisent notre organisation. Une organisation qui, naturellement, se distingue des autres. Toutefois, un regard attentif aux chiffres révèle que nos dépenses internes se sont élevées à 43 000 $. Vous vous demandez peut-être pourquoi un tel montant, et c'est là qu'intervient l'incontournable nécessité de satisfaire des exigences absolument fondamentales. Nous avons récemment ajouté un étage entier à notre bâtiment, un étage exclusivement dédié à notre CEO, afin de garantir que sa vision, sa grandeur et son leadership puissent être nourris dans un environnement qui soit à la hauteur de ses ambitions. Un investissement en infrastructure digne de notre stature.

            En ce qui concerne nos dépenses globales, elles ont atteint 42 000 $, un chiffre en ligne avec l'ampleur de notre croissance. Le coût élevé de l'ajout de cet étage dédié au CEO explique largement cette somme. Mais comprenez bien, cet étage n’est pas simplement un ajout physique : il représente une déclaration, un symbole de notre position dominante sur le marché et de notre volonté d'aller au-delà des attentes. Il est impensable que notre CEO, figure emblématique de notre réussite, ne bénéficie pas de conditions optimales pour prendre des décisions d'une telle importance. Cette dépense, loin d'être un excès, est un investissement stratégique dans la réussite future de notre entreprise, qui n’a que des sommets à atteindre.
            ]],
        ["csc_doc_t"] = [[
            Le 28 septembre 2019, notre entreprise a généré un chiffre d'affaires de 12 500 $, un montant qui pourrait sembler satisfaisant, n'est-ce pas ? Et pourtant, il faut bien reconnaître que nos dépenses internes ont atteint la somme vertigineuse de 32 000 $. Comment expliquer un tel écart, me direz-vous ? Eh bien, nous avons récemment investi dans le confort absolu de nos employés, avec l'ajout d'un étage de détente digne des plus grands spas. Au lieu de se concentrer sur les résultats, nous avons décidé qu'un confort extrême était la clé du succès. Qui aurait cru que les employés auraient besoin de fauteuils massants et de plantes tropicales pour accomplir leur travail ? N'est-ce pas tout simplement révolutionnaire ?

            De plus, les dépenses globales ont grimpé à 34 000 $, preuve évidente de notre approche avant-gardiste. Le confort est tellement devenu une priorité que, dans cet étage luxueux, nos employés n'ont même plus à se soucier de la cafétéria, où Monsieur Anderson, notre cuisinier du jour, prépare des repas d'une finesse incroyable. Bien sûr, cela coûte un peu plus cher, mais tant pis pour les résultats financiers, n'est-ce pas ? Tant que tout le monde est bien nourri et détendu, l'important est là. Et si le chiffre d'affaires en pâtit, eh bien, au moins nos employés peuvent s'endormir sur des coussins en soie après leur déjeuner gastronomique. Voilà la vraie priorité.
            ]]
    }

}