Config = {

    upstress = 5,
    upfatigue = 5,
    upprod = 1,

    mailreceptionlocation = 'office_letter_box_machine',
    goodpileprops = 'office_letter_recep_g',
    badpileprops = 'office_letter_recep_b',
    adminprops = 'v_ind_dc_desk01',
    deliverymailslots = 30,
    minute = 15, -- temps entre chaque livraison

    jobRequired = {
        'accueil',
        'admin'
    },
    jobtoprod = 'accueil',

    -- Liste des courriers
    goodMailItems = {
        "mail_good_1",
        "mail_good_2",
        "mail_good_3",
        "mail_good_4",
        "mail_good_5",
        "mail_good_6",
        "mail_good_7",
        "mail_good_8",
        "mail_good_9",
        "mail_good_10",
        "mail_good_11",
        "mail_good_12",
        "mail_good_13"
    },

    badMailItems = {
        "mail_bad_1",
        "mail_bad_2",
        "mail_bad_3",
        "mail_bad_4",
        "mail_bad_5",
        "mail_bad_6",
        "mail_bad_7",
        "mail_bad_8",
        "mail_bad_9",
        "mail_bad_10"
    },

    wh_readItem = {
        "mail_good_1",
        "mail_good_2",
        "mail_good_3",
        "mail_good_4",
        "mail_good_5",
        "mail_good_6",
        "mail_good_7",
        "mail_good_8",
        "mail_good_9",
        "mail_good_10",
        "mail_good_11",
        "mail_good_12",
        "mail_good_13",
        "mail_bad_1",
        "mail_bad_2",
        "mail_bad_3",
        "mail_bad_4",
        "mail_bad_5",
        "mail_bad_6",
        "mail_bad_7",
        "mail_bad_8",
        "mail_bad_9",
        "mail_bad_10",
        'mail_15a',
        'mail_9b',
        'mail_17c',
        'mail_8d',
        'mail_3e',
        'mail_12f',
        'mail_13g',
        'mail_6h',
        'mail_11i',
        'mail_22j',
        'mail_4k',
        'mail_19l',
        'mail_2m',
        'mail_18n',
        'mail_1o',
        'mail_5p',
        'mail_20q',
        'mail_16r',
        'mail_20s',
        'mail_10t',
        'mail_14u',
        'mail_24v',
        'mail_7x',
    },

}