Config = {

    items = {
        'docimage_recette_boissons',
        'docimage_recette_burger',
        'docimage_recette_frite',
        'docimage_recette_omelette',
        'docimage_recette_salade',
        'docimage_recette_cafe',
        'docimage_nds_bonbonne',
        'docimage_nds_courrier',
        'docimage_nds_livraison',
        'docimage_nds_commande',
        'docimage_code1',
        'docimage_pola_01',
        'docimage_pola_02',
        'docimage_pola_03',
        'docimage_jobdoc_it',
        'docimage_jobdoc_cafet',
        'docimage_jobdoc_archive',
        'docimage_jobdoc_menage',
        'docimage_jobdoc_compta',
        'docimage_jobdoc_accueil',
        'docimage_jobdoc_infirmerie',
        'docimage_jobdoc_communication',
        'docimage_photo_1',
        'docimage_pub',
        'docimage_recette_grosjoint',
        'docimage_useless1',
        'docimage_useless2',
        'docimage_useless4',
        'docimage_useless3',
        'docimage_useless5',
        'docimage_useless6',
        'docimage_useless7',
        'docimage_useless8',
        'docimage_pub2',
        'docimage_pub3',
        'docimage_pub4',
        'docimage_pub6',
        'docimage_pub7',
        'docimage_recette_medicament',
        'docimage_pola_04',
        'docimage_pola_05',
        'docimage_pola_06',
        'docimage_pola_07',
        'docimage_pola_08',
        'docimage_pola_09',
        'docimage_joblist',
        'docimage_code2',
        'docimage_code3',
        'docimage_code4',
        'docimage_code5',
        'docimage_code6',
        

        --ticket
        'it_ticket_ss',
        'it_ticket_rdc',
        'it_ticket_1',
        'it_ticket_2',
        'it_ticket_3',
        'it_ticket_4',
        'it_ticket_5',

    },

}